apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: my-org
  description: My org organization
  links:
    - url: http://www.example.org
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: My Org
    email: info@example.org
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: groups
  description: A collection of all Backstage Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: clusters
  description: A collection of all clusters
spec:
  targets:
    - ./cluster-1.yaml
    - ./cluster-2.yaml
    
